/// <reference types="vitest/config" />
import { readdirSync, statSync } from "node:fs";
import { relative, resolve } from "node:path";
import { defineConfig } from "vite";
import dts from "vite-plugin-dts";
import tsconfigPaths from "vite-tsconfig-paths";

function getEntries(
    dir: string,
    baseDir: string = dir,
): Record<string, string> {
    const entries: Record<string, string> = {};
    const files = readdirSync(dir);

    for (const file of files) {
        const fullPath = resolve(dir, file);
        const stat = statSync(fullPath);

        if (stat.isDirectory()) {
            Object.assign(entries, getEntries(fullPath, baseDir));
        } else if (
            stat.isFile() &&
            file.endsWith(".ts") &&
            !file.endsWith(".d.ts")
        ) {
            const relativePath = relative(baseDir, fullPath);
            const name = relativePath
                .replace(/\.ts$/, "")
                .replace(/\\/g, "/")
                .replace(/\/index$/, ""); // Normalize paths and strip /index for cleaner imports

            entries[name] = fullPath;
        }
    }

    return entries;
}

const typeEntries = getEntries(resolve(__dirname, "src/types"));

const dtsConfig = dts({
    include: ["src/**/*.ts"],
    exclude: ["**/*.test.ts", "**/*.spec.ts"],
    tsconfigPath: "./tsconfig.main.json",
    entryRoot: "src",
});

export default defineConfig({
    plugins: [
        tsconfigPaths({ projects: ["./tsconfig.main.json"] }),
        // Types for src/types are generated by scripts/generate-types.ts using zod-to-ts
        // dts plugin handles non-schema files like utils.ts
        dtsConfig,
    ],
    build: {
        lib: {
            entry: {
                index: "src/index.ts",
                utils: "src/utils.ts",
                ...typeEntries,
            },
            fileName: (_, entryName) => `${entryName}.js`,

            formats: ["es"],
        },
        sourcemap: true,
        rollupOptions: {
            external: ["zod"],
        },
    },
    test: {
        environment: "node",
        typecheck: { enabled: true, checker: "tsc" },
    },
    clearScreen: false,
});
